### ISSUE TITLE
File size reduction idea

### ISSUE THREAD

**Issue by jamesplease** [erikthedeveloper/react-render-watch#2]
:wave: Hi there!

I think we could drop the file size of this lib down by quite a bit (at least half, I think) by using a simplified version of [this approach](https://github.com/facebook/react/blob/15-stable/addons/create-react-class/factory.js#L756) rather than including the Class polyfill.

I might have time to look into this soon, but I figured I would leave the note here in case you wanted to look into it @erikthedeveloper .

Thanks for reading! :v:

**Comment by erikthedeveloper** [comment]
That is a good point to bring up. As I understand you are suggesting to use `createClass({/* ... */})` rather than `extends React.Component`? You're right, that would cut out the need for the class polyfill

This got me thinking... I'm not an expert on the topic, but could it be possible to just assume [require] ES6 classes to already be polyfilled? I can't imagine a use case where someone would pull this lib in and not already be using `class` somewhere along the chain...

This also makes me wonder how many duplicated class [or otherwise] polyfills might be being pulled into projects that pull in libs that depend on such features and publish the ES6+ -> polyfilled ES5 version. An interesting topic to think about. I might poke around this idea when I get some free time.

**Comment by jamesplease** [comment]
> As I understand you are suggesting to use createClass({/* ... */}) rather than extends React.Component? You're right, that would cut out the need for the class polyfill

That is what I was suggesting, but looking now at the transpiled source, I think it may already be doing that 🙂 I opened this issue too soon (that is the last time I open an issue past midnight!)

> This got me thinking... I'm not an expert on the topic, but could it be possible to just assume [require] ES6 classes to already be polyfilled?

I think it is safe to assume that developers using React are also transpiling their app, but I don't think that lets library developers remove the transpile step for certain features, such as `class`, unfortunately. There are two reasons for that:

1. most developers' build steps ignore node_modules for performance
2. transpiled source code that uses reserved keywords (such as `class`) frequently remove that keyword after the build step, since it's not possible polyfill a language-level feature. i.e.; if you look at the built source of this lib, it does not use the keyword `class`; it just uses regular old functions

> This also makes me wonder how many duplicated class [or otherwise] polyfills might be being pulled into projects that pull in libs that depend on such features and publish the ES6+ -> polyfilled ES5 version. An interesting topic to think about. I might poke around this idea when I get some free time.

For things that don't polyfill reserved words, such as, say, Map, I think that the answer is that there is _tons_ of duplication 🙂

**Comment by jamesplease** [comment]
> but looking now at the transpiled source, I think it may already be doing that

🙈 wait, nevermind. I was looking at the transpiled source from me starting to make this change, ahaha. I should go to bed.

It looks like there actually is room for improvement here in terms of file size. I think we could get it around 200 bytes, which is pretty cool.

**Comment by erikthedeveloper** [comment]
I played around with this idea of pulling in `create-react-class` but didn't have much luck. I thought it was working wonders until I realized I had left `create-react-class` as an external for Rollup haha... Fixing that shot the build size up to something like `9k`.

@jamesplease I'll leave this open for a bit in case you have another approach in mind you want to play with.

**Comment by jamesplease** [comment]
Yo @erikthedeveloper ! My idea here wasn’t to pull in that actual function, or to add any external deps. That function is bloated with a lot of things, such as mixins, that this lib probably doesn’t need to support. I was thinking of drawing inspiration from that lib to write a small function that acts as the smallest way to create a react class.

I think that could even be made into cool npm module for lib authors.

I can take a look sometime (it may be a week or two though 😀 )

**Comment by erikthedeveloper** [comment]
@jamesplease I'm going to go ahead and close this. If you have success with that minimal `createReactClass` replacement lib, ping me and I'll be happy to check it out!
